<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository {

    public function getByTipo($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT b,t,oa,o,a FROM AppBundle:Banner b ' .
                        'JOIN b.tipo t ' .
                        'JOIN b.ofertaAuto oa ' .
                        'JOIN oa.oferta o ' .
                        'JOIN oa.auto a ' .
                        'WHERE t.id = :id '
                )->setParameter('id', $id);
        $result = $query->getSingleResult();
        return $result;
    }
    
}
